---
- name: Single play example - install nginx and start service
  hosts: g1
  become: yes
  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Ensure nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
